### ISSUE TITLE
I2C NAK

### ISSUE THREAD

**Issue by hartytp** [quartiq/kasli-i2c#6]
Trying to use `kasli-i2c` on a Kasli v1.1 since https://github.com/quartiq/kasli-i2c/commit/1b86a259cc5e705c1b5025639bd4d9aff2da0fca gives errors like

```
Traceback (most recent call last):
  File "/miniconda/envs/devenv/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/miniconda/envs/devenv/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/kasli_get_mac.py", line 21, in <module>
    with bus.enabled("LOC0"):
  File "/miniconda/envs/devenv/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/workspace/kasli.py", line 44, in enabled
    self.enable(*ports)
  File "/workspace/kasli.py", line 40, in enable
    self.write_single(addr, bits[addr])
  File "/workspace/i2c_bitbang.py", line 221, in write_single
    raise I2CNACK("Address Write NACK", addr)
pyftdi.i2c.I2cNackError: [Errno Address Write NACK] 112
```

@jordens am I right in thinking that this relates to hardware changes for v2.0? AFAICT for v2.0 we added a second I2C reset line going to the FPGA. This is ORd with the FT232 RESET line using FETs, resulting in a polarity inversion compared with v1.x.  i.e. on v1.1 BDBUS 5 directly drives the active-low TCA9548 reset, while on v2.x it drives it via an inverter, so BDBUS 5 is active-high reset.

![image](https://user-images.githubusercontent.com/21218399/102256287-1da90500-3f03-11eb-9a28-164a62427b2d.png)

The current code reflects an active-high reset https://github.com/quartiq/kasli-i2c/blob/1b86a259cc5e705c1b5025639bd4d9aff2da0fca/i2c_bitbang.py#L33-L38

The previous code reflects an active-low reset https://github.com/quartiq/kasli-i2c/blob/df6a2dea4d78dc1f49a94d51e465e0cb01759951/i2c_bitbang.py#L33-L38

Does that sound about right @jordens or have I got the wrong end of the stick? If so, do you have preferences on a fix (e.g. pass a reset polarity param into `I2C`'s constructor that's set based on a kasli hw-rev)?

**Comment by jordens** [comment]
Yes. I had flagged that on the kasli repo already. If you need support for v1.1, it should be a backward compatible approach. Auto detecting doesn't seem to complicated (try talking to the switch, if it fails try the other reset polarity). But double check whether the reset pin has moved on the ftdi port since v1.1. Might not even need Auto detection then.

**Comment by hartytp** [comment]
Ack. The pin hasn’t moved. There are enough 1.x around that I think support is worthwhile (particularly for flashing EEMs).

I’ll have a think about autodetect and submit a pr if we find a nice approach.
